name = "pubdesk-rendezvous"
main = "src/index.js"
compatibility_date = "2024-06-01"

# Workers Free tier: 100,000 requests/day.
# This Worker only handles peer discovery metadata, not sync data.

[[kv_namespaces]]
binding = "PUBDESK_PEERS"
id = "fe7f289393b743fba724bbacc81b77a2"
preview_id = "23b923b839084258b8581a90bfcb1f18"
